image: maven:3-jdk-8

stages:
  - deploy

pages:
  stage: deploy
  script:
  - cd docs
  - mkdir html
  - java -jar docs_widoco.jar -ontFile ../mainzedmetadata.ttl -outFolder html/ -rewriteAll -uniteSections -webVowl -confFile config/mainzedmetadata.properties
  - mv index.html html/
  - mv classtree.js html/
  - mv html ../public 
  artifacts:
    paths:
    - public
  only:
  - master

