name: Ontology Documentation CI

on: 
  push: 
      branches:
          - master
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev python3-pip -y
         sudo apt-get install asciidoctor ruby -y
         sudo gem install --pre asciidoctor-pdf
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode
         mkdir docss
         cd docss
         pylode -i ../mainzedmetadata.ttl -o index.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docss/
